{
 "title": "AAVE awstETH risks",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "🥇 BIN 1 risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"1\"}"
    }
   ]
  },
  {
   "title": "🥇 BIN 2 risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"2\"}"
    }
   ]
  },
  {
   "title": "🥈 BIN 3 risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"3\"}"
    }
   ]
  },
  {
   "title": "🥉 BIN 4 risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"4\"}"
    }
   ]
  },
  {
   "title": "🥇 AAVE risks BIN 1",
   "type": "timeseries",
   "description": "Users with e-mode and with >=80% of collateral - wstETH, and >= 80% of debt - ETH",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"1\"}",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 1 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals{pair=\"wstETH-WETH\",bin=\"1\"} / on (pair,bin) group_left aave_bot_collaterals:total",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "🥇 AAVE risks BIN 2",
   "type": "timeseries",
   "description": "Users without e-mode and with >=80% of collateral - wstETH, and >= 80% of debt - ETH",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"2\"}",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 2 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals{pair=\"wstETH-WETH\",bin=\"2\"} / on (pair,bin) group_left aave_bot_collaterals:total",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "🥈 AAVE risks BIN 3",
   "type": "timeseries",
   "description": "Users with wstETH collateral and >=80% debt - not ETH",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"3\"}",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 3 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals{pair=\"wstETH-WETH\",bin=\"3\"} / on (pair,bin) group_left aave_bot_collaterals:total",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "🥉 AAVE risks BIN 4",
   "type": "timeseries",
   "description": "All other AAVE users with wstETH collateral",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{pair=\"wstETH-WETH\",bin=\"4\"}",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 4 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals{pair=\"wstETH-WETH\",bin=\"4\"} / on (pair,bin) group_left aave_bot_collaterals:total",
     "legendFormat": "{{zone}}"
    }
   ]
  }
 ]
}