{
 "title": "AAVE bot",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "🥇 BIN 1 risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{bin=\"1\"}"
    }
   ]
  },
  {
   "title": "🥈 BIN 2 risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{bin=\"2\"}"
    }
   ]
  },
  {
   "title": "🥉 BIN 3 risks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{bin=\"3\"}"
    }
   ]
  },
  {
   "title": "🥇 AAVE risks BIN 1",
   "type": "timeseries",
   "description": "AAVE users with >=80% collaterals - stETH and  >=80% debt - ETH",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{bin=\"1\"}",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 1 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals{bin=\"1\"} / on (bin) group_left aave_bot_collaterals:total",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "🥈 AAVE risks BIN 2",
   "type": "timeseries",
   "description": "AAVE users with stETH collateral and >=80% debt - not ETH",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{bin=\"2\"}",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 2 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals{bin=\"2\"} / on (bin) group_left aave_bot_collaterals:total",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "🥉 AAVE risks BIN 3",
   "type": "timeseries",
   "description": "All the others AAVE users with stETH collateral",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals:risky:percent{bin=\"3\"}",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 3 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aave_bot_collaterals{bin=\"3\"} / on (bin) group_left aave_bot_collaterals:total",
     "legendFormat": "{{zone}}"
    }
   ]
  }
 ]
}