{
 "title": "AAVE risks bot",
 "description": "https://www.notion.so/AAVE-collaterals-bot-7510af03a724430dafabb86109b941e8",
 "tags": [
  "bot",
  "automation",
  "apps"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "container", "query": "aave-collaterals-bot" },
   { "name": "service", "query": "aave-collaterals-bot" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(aave_bot_build_info, env)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(aave_bot_build_info{env=~\"$env\"}, source)"
    }
   },
   { "name": "search", "label": "Search query" },
   {
    "name": "provider",
    "query": {
     "query": "label_values(aave_bot_eth_rpc_requests_total{env=~\"$env\",source=~\"$source\"}, provider)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Build info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "aave_bot_build_info" }
     ]
    },
    {
     "title": "Branch",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "aave_bot_build_info" }
     ]
    },
    {
     "title": "Commit",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "aave_bot_build_info" }
     ]
    },
    {
     "title": "Python",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "aave_bot_build_info" }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Container uptime",
   "type": "stat",
   "description": "Bot container uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"$container\",env=~\"$env\",source=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Time since the last report",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - aave_bot_processing_finished_seconds"
    }
   ]
  },
  {
   "title": "Fails count",
   "type": "stat",
   "description": "Count of fails inside the app modules",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aave_bot_app_errors_total{env=~\"$env\",source=~\"$source\"}[$__range])",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Average fetch duration",
   "type": "stat",
   "description": "Average fetch duration",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aave_bot_fetch_duration{env=~\"$env\",source=~\"$source\"}[$__range])"
    }
   ]
  },
  {
   "title": "ETH RPC requests count",
   "type": "stat",
   "description": "Count of requests to ETH RPC node ",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(aave_bot_eth_rpc_requests_total{env=~\"$env\",source=~\"$source\"}[$__range])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  { "title": "Requests by $provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "provider" },
  {
   "title": "RPC requests duration",
   "type": "heatmap",
   "description": "Duration of requests to the RPC provider",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(aave_bot_eth_rpc_requests_duration_bucket{env=~\"$env\",source=~\"$source\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RPC requests errors",
   "type": "timeseries",
   "description": "Number of request errors to the RPC provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(aave_bot_eth_rpc_requests_total{code!=\"0\",env=~\"$env\",source=~\"$source\"}[1m])) by (code)",
     "legendFormat": "code={{code}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json | line_format \"[{{.levelname}}] {{.message}}\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json |= \"ERROR\" | line_format \"[{{.levelname}}] {{.message}}\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Resources usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Cumulative cpu time consumed",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(irate(container_cpu_user_seconds_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100) + (sum(irate(container_cpu_system_seconds_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100)",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{env=~\"$env\",source=~\"$source\",name=~\"$container\"}) by (name)",
       "legendFormat": "mem"
      }
     ]
    },
    {
     "title": "Opened FDs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_file_descriptors{env=~\"$env\",source=~\"$source\",name=~\"$container\"}",
       "legendFormat": "FDs"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)) + (sum(irate(container_network_transmit_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name))",
       "legendFormat": "net"
      }
     ]
    }
   ]
  },
  {
   "title": "Python stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python GC uncollectable",
     "type": "timeseries",
     "description": "Uncollectable objects count found during GC",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "increase(python_gc_objects_uncollectable_total{service=\"$service\",env=~\"$env\",source=~\"$source\"}[$__rate_interval])",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Python GC collected",
     "type": "timeseries",
     "description": "Objects collected during GC",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "targets": [
      {
       "expr": "increase(python_gc_objects_collected_total{service=\"$service\",env=~\"$env\",source=~\"$source\"}[$__rate_interval])",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Python GC collections",
     "type": "timeseries",
     "description": "Number of times this generation was collected",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "targets": [
      {
       "expr": "increase(python_gc_collections_total{service=\"$service\",env=~\"$env\",source=~\"$source\"}[$__rate_interval])",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Process file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "process_open_fds{service=\"$service\",env=~\"$env\",source=~\"$source\"}",
       "legendFormat": "Open FD"
      },
      {
       "expr": "process_max_fds{service=\"$service\",env=~\"$env\",source=~\"$source\"}",
       "legendFormat": "Max FD"
      }
     ]
    },
    {
     "title": "Process resident memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{service=\"$service\",env=~\"$env\",source=~\"$source\"}"
      }
     ]
    },
    {
     "title": "Process virtual memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{service=\"$service\",env=~\"$env\",source=~\"$source\"}"
      }
     ]
    }
   ]
  }
 ]
}