{
 "title": "AAVE bot",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "🥇 BIN 1 risks %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aave_bot_collateral_percentage{bin=\"1\", zone=~\"C|D|liquidation\"})"
    }
   ]
  },
  {
   "title": "🥈 BIN 2 risks %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aave_bot_collateral_percentage{bin=\"2\", zone=~\"C|D|liquidation\"})"
    }
   ]
  },
  {
   "title": "🥉 BIN 3 risks %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aave_bot_collateral_percentage{bin=\"3\", zone=~\"C|D|liquidation\"})"
    }
   ]
  },
  {
   "title": "🥇 AAVE risks BIN 1",
   "type": "timeseries",
   "description": "AAVE users with >=80% collaterals - stETH and  >=80% debt - ETH",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(aave_bot_collateral_percentage{bin=\"1\", zone=~\"C|D|liquidation\"})",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 1 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "aave_bot_collateral_percentage{bin=\"1\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "🥈 AAVE risks BIN 2",
   "type": "timeseries",
   "description": "AAVE users with stETH collateral and >=80% debt - not ETH",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(aave_bot_collateral_percentage{bin=\"2\", zone=~\"C|D|liquidation\"})",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 2 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "aave_bot_collateral_percentage{bin=\"2\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "🥉 AAVE risks BIN 3",
   "type": "timeseries",
   "description": "All the others AAVE users with stETH collateral",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(aave_bot_collateral_percentage{bin=\"3\", zone=~\"C|D|liquidation\"})",
     "legendFormat": "C+D+liquidation"
    }
   ]
  },
  {
   "title": "Bin 3 zones overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "aave_bot_collateral_percentage{bin=\"3\"}",
     "legendFormat": "{{zone}}"
    }
   ]
  }
 ]
}