scrape_configs:
  - job_name: "mainnet"
    static_configs:
      - targets: ["bot-mainnet:8080"]
        labels:
          service: "aave-mainnet-bot"
          source: "aave-mainnet-bot"
          env: "prod"
