scrape_configs:
  - job_name: "polygon"
    static_configs:
      - targets: ["bot-polygon:8080"]
        labels:
          service: "aave-polygon-bot"
          source: "aave-polygon-bot"
          env: "prod"
