name: Linters

on: push

jobs:
  python:
    uses: lidofinance/linters/.github/workflows/python.yml@master
    with:
      python-version: 3.10.6
      dirs: src
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
