name: Linters

on: push

jobs:
  python:
    uses: lidofinance/linters/.github/workflows/python.yml@master
    with:
      dirs: src
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
